mutation Login($payload: LoginDetailInput!) {
  login(detail: $payload) {
    accessToken
    user {
      id
      username
    }
  }
}

mutation Register($payload: RegisterDetailInput!) {
  register(detail: $payload) {
    id
  }
}
