mutation CreateNewLink($payload: CreateLinkInput!) {
  createLink(data: $payload) {
    id
  }
}

query FindLinksOfUserByUserId($payload: FindLinksOfUserByUserIdInput!) {
  findLinksOfUserByUserId(data: $payload) {
    id
    order
    isDraft
    isVisible
    title
    url
  }
}

mutation UpdateLink($payload: UpdateLinkInput!) {
  updateLink(data: $payload) {
    id
    isVisible
    title
    url
  }
}

mutation ReorderLinksOfUser($payload: ReorderLinksOfUserInput!) {
  reorderLinksOfUser(data: $payload) {
    id
    order
    isDraft
    isVisible
    title
    url
  }
}

mutation DeleteLinkById($payload: DeleteLinkInput!) {
  deleteLinkById(data: $payload)
}

query FindUserByUsername($payload: FindUserByUsernameInput!) {
  findUserByUsername(username: $payload) {
    id
    username
    displayName
    bio
    links {
      id
      title
      url
      logoUrl
    }
  }
}

mutation UpdateProfile($payload: UpdateProfileInput!) {
  updateProfile(data: $payload) {
    id
    displayName
    bio
  }
}
