query FindAllCategory {
  categories {
    id
    type
  }
}

mutation OnboardUser($payload: OnboardUserInput!) {
  onboardUser(data: $payload) {
    id
    status
    username
    displayName
    categoryId
  }
}
