query Company {
  company {
    name
    summary
    links {
      website
    }
  }
}

query Users {
  users {
    id
    name
    rocket
  }
}

query LaunchList {
  launches {
    mission_name
    launch_year
    rocket {
      rocket_name
      rocket_type
    }
  }
}
