import type { NextPage } from 'next';
import Head from 'next/head';

import { Container, Footer } from '@common/components';
import {
  Title,
  Description,
  NextInformation,
} from '@modules/next-template/sections';

const Home: NextPage = () => {
  const cards: Card[] = [
    {
      href: 'https://nextjs.org/docs',
      title: `Documentation`,
      description: 'Find in-depth information about Next.js features and API.',
    },
    {
      href: 'https://nextjs.org/learn',
      title: `Learn`,
      description: 'Learn about Next.js in an interactive course with quizzes!',
    },
    {
      href: 'https://github.com/vercel/next.js/tree/canary/examples',
      title: `Examples`,
      description: 'Discover and deploy boilerplate example Next.js projects.',
    },
    {
      href: 'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
      title: `Deploy`,
      description:
        'Instantly deploy your Next.js site to a public URL with Vercel.',
    },
  ];

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container type="main">
        <Title />
        <Description />
        <NextInformation cards={cards} />
      </Container>
      <Footer />
    </Container>
  );
};

export default Home;
