import type { NextPage } from 'next';
import { VStack } from '@chakra-ui/react';
import { useTranslation } from 'react-i18next';
import {
  SectionContainer,
  SectionHWrapper,
  HomeContainer,
} from '@src/common/components';
import { Hero } from '@src/modules/Home/components';
import { GlobalRoute } from '@src/constants/PageRoutes';

const Home: NextPage = () => {
  const { t } = useTranslation('home');
  const head = {
    title: 'Create Next App',
    metas: [
      {
        name: 'description',
        content: 'Generated by create next app',
      },
    ],
    links: [
      {
        rel: 'icon',
        href: '/favicon.ico',
      },
    ],
  };

  const heros = [
    {
      title: t('banner.title'),
      subtitle: t('banner.subtitle'),
      cta: t('banner.cta'),
      link: GlobalRoute.Root,
      src: 'assets/heros/shapes.svg',
      alt: t('banner.alt'),
    },
    {
      title: t('custome-profile.title'),
      subtitle: t('custome-profile.subtitle'),
      cta: t('custome-profile.cta'),
      link: GlobalRoute.Root,
      src: 'assets/heros/phone.svg',
      alt: t('custome-profile.alt'),
    },
    {
      title: t('game-status.title'),
      subtitle: t('game-status.subtitle'),
      cta: t('game-status.cta'),
      link: GlobalRoute.Root,
      src: 'assets/heros/squares.svg',
      alt: t('game-status.alt'),
    },
    {
      title: t('share-anywhere.title'),
      subtitle: t('share-anywhere.subtitle'),
      cta: t('share-anywhere.cta'),
      link: GlobalRoute.Root,
      src: 'assets/heros/shapes2.svg',
      alt: t('share-anywhere.alt'),
    },
  ];

  return (
    <HomeContainer head={head}>
      <VStack flex={1} justify="center">
        {heros.map((hero, index) => {
          return (
            <SectionContainer key={index}>
              <SectionHWrapper
                flexDirection={index % 2 === 0 ? 'row' : 'row-reverse'}
              >
                <Hero
                  title={hero.title}
                  subtitle={hero.subtitle}
                  cta={hero.cta}
                  link={hero.link}
                  src={hero.src}
                  alt={hero.alt}
                  alignItems={index % 2 === 0 ? 'flex-end' : 'flex-start'}
                  type={index === 0 ? 'h1' : 'h2'}
                />
              </SectionHWrapper>
            </SectionContainer>
          );
        })}
      </VStack>
    </HomeContainer>
  );
};

export default Home;
