import type { NextPage } from 'next';
import { useTranslation } from 'react-i18next';

import { VStack } from '@chakra-ui/react';
import { PageContainer } from '@src/common/components';
import {
  Title,
  Description,
  NextInformation,
} from '@modules/NextTemplate/sections';

const Home: NextPage = () => {
  const { t } = useTranslation('next-template');
  const head = {
    title: 'Create Next App',
    metas: [
      {
        name: 'description',
        content: 'Generated by create next app',
      },
    ],
    links: [
      {
        rel: 'icon',
        href: '/favicon.ico',
      },
    ],
  };

  const cards: Card[] = [
    {
      href: 'https://nextjs.org/docs',
      title: t('cards.0.title'),
      description: t('cards.0.description'),
    },
    {
      href: 'https://nextjs.org/learn',
      title: t('cards.1.title'),
      description: t('cards.1.description'),
    },
    {
      href: 'https://github.com/vercel/next.js/tree/canary/examples',
      title: t('cards.2.title'),
      description: t('cards.2.description'),
    },
    {
      href: 'https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app',
      title: t('cards.3.title'),
      description: t('cards.3.description'),
    },
  ];

  return (
    <PageContainer head={head}>
      <VStack flex={1} justify="center" align="center" gap="2rem">
        <Title />

        <Description />
        <NextInformation cards={cards} />
      </VStack>
    </PageContainer>
  );
};

export default Home;
