pipeline {
    agent any
    stages {
        stage('Git check out') {
            steps{
                echo 'Git check out...'
                // Get source code from a GitHub repository
                git branch: env.BRANCH_NAME, url:'https://github.com/A-Comosus/comosus-client.git'
            }
        }
        stage('Install dependencies') {
            steps {
                echo 'Install dependencies...'
                sh 'npm install'
            }
        }

        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'npm run test:coverage'
            }
        }
        
        stage('Checking for linter error') {
            steps {
                echo 'Checking for linter error....'
                sh 'npm run lint'
            }
        }
         stage('Build') {
            steps {
                echo 'Building....'
                sh 'npm run codegen'
                sh 'npm run build'
            }
        }
    }
}