name: Deploy to ECR

on:
  push:
    branches:
    - 'develop'
    - 'ci-cd/*Alex'
  pull_request:
  workflow_run:
    workflows:
      - Cypress Tests
      - Sanity Check
    types: [completed]
    branches:
    - 'develop'
    - 'ci-cd/*Alex'

jobs:
  
  build:
    environment: uat-deployment
    
    name: Build Image
    runs-on: ubuntu-latest
    if:  github.event.workflow_run.conclusion == 'success'
    steps:

    - name: Check out code
      uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: a-comosus-uat-frontend
        IMAGE_TAG: ${GITHUB_RUN_NUMBER}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG