name: Deploy to ECR

on:
  push:
    branches:
    - 'develop'
    - 'ci-cd/*Alex'
  #workflow_run:
  #  workflows: [Cypress Tests]
  #  types: [completed]
  #  branches:
  #  - 'develop'
  #  - 'ci-cd/*Alex'

jobs:
  build:
    environment: uat-deployment
    
    name: Build Image
    runs-on: ubuntu-latest
    #if:  github.event.workflow_run.conclusion == 'success'
    steps:
      - name: test environment variable
      - run: echo ${env.GITHUB_JOB}

    # - name: Check out code
    #   uses: actions/checkout@v3
    
    # - name: Configure AWS credentials
    #   uses: aws-actions/configure-aws-credentials@v1
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     aws-region: ap-southeast-2

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v1

    # - name: Build, tag, and push image to Amazon ECR
    #   env:
    #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
    #     ECR_REPOSITORY: a-comosus-uat-frontend
    #     IMAGE_TAG: 1999
    #     N_G_ENDPOINT: https://api.uat.a-comosus.link/graphql/
    #   run: |
    #     docker build --build-arg N_G_ENDPOINT=$N_G_ENDPOINT -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f Dockerfile.Alex .
    #     docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG