name: Push image to ECR and deploy to EKS

on:
  push:
    branches:
      - 'develop'
      - 'ci-cd/update-github-action-Alex'

jobs:
  build:
    environment: uat-deployment

    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: a-comosus-uat-frontend
          N_G_ENDPOINT: ${{ secrets.N_G_ENDPOINT }}
          N_R_SITE_KEY: ${{ secrets.N_R_SITE_KEY }}
        run: |
          docker build --build-arg N_G_ENDPOINT=$N_G_ENDPOINT --build-arg N_R_SITE_KEY=$N_R_SITE_KEY -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_RUN_NUMBER -f Dockerfile.Alex .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_RUN_NUMBER

      - name: Check out code
        uses: actions/checkout@v3
        with:
          repository: A-Comosus/comosus-uat-module-terraform
          ref: main
          token: ${{ secrets.PAT }}

      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.0

      - name: Terraform init && apply
        run: terraform init

      - name: Terraform apply
        run: terraform apply -target module.frontend -var-file=uat-var.tfvars -var="frontend_image_tage=${GITHUB_RUN_NUMBER}" -auto-approve
